# -*- coding: utf-8 -*-
"""inference_cnn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12WHDg83a5ePuYssUpDyljf2UWVVBvFRa
"""

import torch
import torch.nn as nn
import torchvision.transforms as transforms
from PIL import Image

# ==============================================================================
# 1. 모델 구조 정의 (SpeechAnxietyCNN Large, Dropout 0.5)
# ==============================================================================
class SpeechAnxietyCNN(nn.Module):
    def __init__(self, dropout=0.5, size='large'):
        super(SpeechAnxietyCNN, self).__init__()

        sizes = {
            'small':  [32, 64, 128],
            'medium': [64, 128, 256],
            'large':  [128, 256, 512]
        }
        filters = sizes[size]

        self.features = nn.Sequential(
            nn.Conv2d(3, filters[0], kernel_size=3, padding=1),
            nn.BatchNorm2d(filters[0]),
            nn.ReLU(),
            nn.MaxPool2d(2, 2),

            nn.Conv2d(filters[0], filters[1], kernel_size=3, padding=1),
            nn.BatchNorm2d(filters[1]),
            nn.ReLU(),
            nn.MaxPool2d(2, 2),

            nn.Conv2d(filters[1], filters[2], kernel_size=3, padding=1),
            nn.BatchNorm2d(filters[2]),
            nn.ReLU(),
            nn.MaxPool2d(2, 2),
        )

        self.gap = nn.AdaptiveAvgPool2d(1)

        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear(filters[2], 256),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(256, 3)
        )

    def forward(self, x):
        x = self.features(x)
        x = self.gap(x)
        x = self.classifier(x)
        return x

# ==============================================================================
# 2. 학습된 가중치 로드
# ==============================================================================
model = SpeechAnxietyCNN(dropout=0.5, size='large')
model.load_state_dict(torch.load('best_size_large.pth', map_location='cpu'))
model.eval()

# ==============================================================================
# 3. 이미지 전처리
# ==============================================================================
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5, 0.5, 0.5],
                        std=[0.5, 0.5, 0.5])
])

# ==============================================================================
# 4. 추론 함수
# ==============================================================================
THRESHOLDS = {
    'prolongation': 0.4,
    'tremor': 0.3,
    'energy': 0.3,
}

def predict(image_path):
    img = Image.open(image_path).convert('RGB')
    img = transform(img).unsqueeze(0)

    with torch.no_grad():
        output = model(img)
        probs = torch.sigmoid(output)

    result = {
        'prolongation': round(probs[0][0].item(), 4),
        'tremor':       round(probs[0][1].item(), 4),
        'energy':       round(probs[0][2].item(), 4)
    }

    scores = {
        'prolongation_score': round(100 * (1 - result['prolongation']), 1),
        'tremor_score':       round(100 * (1 - result['tremor']), 1),
        'energy_score':       round(100 * (1 - result['energy']), 1)
    }

    return result, scores

# ==============================================================================
# 5. 사용 예시
# ==============================================================================
image_path = 'sample.png'  # 멜-스펙트로그램 이미지 경로
probs, scores = predict(image_path)

print("확률값:", probs)
print("점수:", scores)